name: CPU Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .[p2p]
    - name: Do CPU tests with pytest
      run: |
        pytest -v -m "cpu" tests/
